### ISSUE TITLE
Ошибка cc2531 zigbee 

### ISSUE THREAD

**Issue by Alxprv** [sprut/Hub#172]
** Подробное описание ошибки **
E | 2020-07-06 | 06:06:34.876 | o.makesimple.ZigBee.dongle.cc2531.network.packet.f 220 | Packet parsing failed due to exception.
org.makesimple.ZigBee.dongle.cc2531.network.packet.ZToolParseException: Read -1 from input stream while reading packet!
  at org.makesimple.ZigBee.dongle.cc2531.network.packet.f.b(SourceFile:248)
  at org.makesimple.ZigBee.dongle.cc2531.network.packet.f.a(SourceFile:233)
  at org.makesimple.ZigBee.dongle.cc2531.network.packet.f.a(SourceFile:204)
  at org.makesimple.ZigBee.dongle.cc2531.network.packet.e.run(SourceFile:64)
  at java.lang.Thread.run(Thread.java:748)

** Как воспроизвести ? **
Сама в логе появляется раз в сутки

**Comment by Alxprv** [comment]
Стик WB, на версии 1.6.4. валится очень часто:

E | 2020-08-19 | 08:56:07.852 | o.m.Z.dongle.cc2531.network.packet.f     220 | Packet parsing failed due to exception.
org.makesimple.ZigBee.dongle.cc2531.network.packet.ZToolParseException: Read -1 from input stream while reading packet!
	at org.makesimple.ZigBee.dongle.cc2531.network.packet.f.b(SourceFile:248)
	at org.makesimple.ZigBee.dongle.cc2531.network.packet.f.a(SourceFile:233)
	at org.makesimple.ZigBee.dongle.cc2531.network.packet.f.g(SourceFile:272)
	at org.makesimple.ZigBee.dongle.cc2531.network.packet.f.a(SourceFile:201)
	at org.makesimple.ZigBee.dongle.cc2531.network.packet.e.run(SourceFile:66)
	at java.lang.Thread.run(Thread.java:748)
E | 2020-08-19 | 08:57:54.506 | o.m.Z.dongle.cc2531.network.packet.f     220 | Packet parsing failed due to exception.
org.makesimple.ZigBee.dongle.cc2531.network.packet.ZToolParseException: Read -1 from input stream while reading packet!
	at org.makesimple.ZigBee.dongle.cc2531.network.packet.f.b(SourceFile:248)
	at org.makesimple.ZigBee.dongle.cc2531.network.packet.f.a(SourceFile:233)
	at org.makesimple.ZigBee.dongle.cc2531.network.packet.f.a(SourceFile:204)
	at org.makesimple.ZigBee.dongle.cc2531.network.packet.e.run(SourceFile:66)
	at java.lang.Thread.run(Thread.java:748)
