### ISSUE TITLE
Не подключается Apple Home

### ISSUE THREAD

**Issue by dkozickis** [sprut/Hub#252]
**Подробное описание ошибки**
Хаб зло ругается когда пытаюсь Apple Home его тыкать

```
11:34:37 Terminated homekit connection from /10.100.200.104:52703 
11:34:37 Terminated homekit connection from /10.100.200.107:49304 
11:34:37 Excepton encountered while verifying pairing 
11:34:37 Excepton encountered while verifying pairing 
11:34:29 New homekit connection from /10.100.200.104:52703 
11:34:29 New homekit connection from /10.100.200.107:49304
```

Пробовал чистить коннекты, пользователей, перезагружать, отключать контроллеры и перезагружать - все еще ошибка.

**Скриншоты/ Логи**

```
I | 2020-09-02 | 11:34:29.585 | org.makesimple.SprutHub.Homekit.http.a   54  | New homekit connection from /10.100.200.107:49304
I | 2020-09-02 | 11:34:29.592 | org.makesimple.SprutHub.Homekit.http.a   54  | New homekit connection from /10.100.200.104:52703
E | 2020-09-02 | 11:34:37.276 | org.makesimple.SprutHub.Homekit.a.c      131 | Excepton encountered while verifying pairing
java.lang.NullPointerException: null
	at javax.xml.bind.DatatypeConverterImpl._printBase64Binary(DatatypeConverterImpl.java:763)
	at javax.xml.bind.DatatypeConverterImpl.printBase64Binary(DatatypeConverterImpl.java:586)
	at javax.xml.bind.DatatypeConverter.printBase64Binary(DatatypeConverter.java:612)
	at org.makesimple.SprutHub.Homekit.pairing.f.a(SourceFile:114)
	at org.makesimple.SprutHub.Homekit.pairing.f.a(SourceFile:58)
	at org.makesimple.SprutHub.Homekit.a.c.d(SourceFile:127)
	at org.makesimple.SprutHub.Homekit.a.c.a(SourceFile:57)
	at org.makesimple.SprutHub.Homekit.a.a.a(SourceFile:60)
	at org.makesimple.SprutHub.Homekit.http.a.a(SourceFile:74)
	at org.makesimple.SprutHub.Homekit.http.a.channelRead0(SourceFile:17)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:316)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Пожалуйста, заполните следующую информацию:**
  - Версия: Sprut 1.6.4b

**Comment by MakeSimpleOrg** [comment]
Эту ошибку исправил в 1.6.5, будет писать теперь что пользователь неизвестен, без ошибки.
Но проблема в другом, хаб не знает такого пользователя. После очистки пользователей всегда необходимо удалять мост из хомкита и делать новый.
