### ISSUE TITLE
Ошибка в (бета?) контроллере Fibaro

### ISSUE THREAD

**Issue by Savier** [sprut/Hub#2816]
### Подробное описание ошибки
Устройства подключеные через контроллер Fibaro нормально управляются и отображают состояние, но в состоянии "Нет ответа"

### Как воспроизвести ?
1. Имеем несколько (12) уcтройств Fibaro FGRGB441 (контроллер освещения), хаб Fibaro Home Center Lite. Устройства нормально управляются и отображаются на родном хабе.
2. На Sprut Hub 2 добавляем контроллер типа Fibaro. Заполняем все поля с необходимой информацией, включаем контроллер. Все устройства сразу появляются. Выглядят и работают нормально
3. Перезагружаем SprutHub.
4. На каждом fibaro-устройстве красная пометка "Нет ответа"
5. При нажатии на устройства свет включается, яркость регулируется. При включении/выключении света выключателем или на родном хабе Fibaro состояние отображается на Sprut Hub 2.
6. При попытке управлять голосом через мост Яндекс, Алиса правильно включает/выключает/меняет яркость но всегда отвечает "Извините, не получилось, надо сначала включить устройство"
7. Останавливал/запускал контроллер, перезагружал родной хаб Fibaro, затем Sprut.Hub 2 - ничего не меняется, все так же "Нет ответа". 
8. Помогает - в контроллере выбрать "удалить все аксессуары", затем остановить/запустить контроллер. Ситуация приходит к результату пункта 2. При наличии моста с яндексом требуется еще удалить spruthub на алисе/подключить снова, иначе устройства задваиваются.

### Ожидаемое поведение
После перезагрузки хаба на устройствах не будет пометки "Нет ответа", Алиса будет понимать что команда исполнена успешно.

### Скриншоты/ Логи
Логи забиты сообщениями (несколько раз в секунду)

```
E | 2023-12-15 | 07:43:27.822 | org.makesimple.SprutHub.Model.CLink      346 | Fibaro_1/74/Hue/
java.lang.ClassCastException: java.lang.Double cannot be cast to vS
	at vQ.b(SourceFile:331)
	at vQ.a(SourceFile:319)
	at vQ.b(SourceFile:338)
	at vQ.a(SourceFile:319)
	at wi.c(SourceFile:230)
	at vQ.b(SourceFile:548)
	at vQ.g(SourceFile:380)
	at pO.w(SourceFile:608)
	at pO.A(SourceFile:113)
	at zX$b.run(SourceFile:537)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at zS$b.b(SourceFile:561)
	at zS$b.run(SourceFile:689)
	at zT$a.a(SourceFile:1471)
	at zT$a.run(SourceFile:1503)
	at java.lang.Thread.run(Thread.java:750)

```

### Пожалуйста, заполните следующую информацию:
- Sprut.hub 2, 1.9.9 (11367) A3E608F3234A8820
- Мой телеграм [@IamSav](https://t.me/IamSav) готов предоставить необходимую информацию, помочь с отладкой, являюсь опытным разработчиком.

### Дополнительные материалы
Поиск в чатах поддержки по слову Fibaro выдает практически только такие же случаи с ноября 2022, при этом непонятно в какой чат писать об этом контроллере, насколько я понимаю ZWave это не то, страницы о нем в вики также не нашел.

<img width="896" alt="image" src="https://github.com/sprut/Hub/assets/1430977/7890f80e-287e-4e37-b071-3282e91ce86c">

**Comment by aleksandr-semenov-dbp** [comment]
Судя по всему контроллер решает что статус "не отвечает" уже после запроса к родному контроллеру `/api/devices?enabled=true` Вот кусочек ответа про устройство в таком состоянии, если скажете что смущает контроллер, я мог бы проверить
```
  {
    "id": 21,
    "name": "Спальня кровать",
    "roomID": 4,
    "type": "com.fibaro.FGRGBW441M",
    "baseType": "com.fibaro.colorController",
    "enabled": true,
    "visible": true,
    "isPlugin": false,
    "parentId": 20,
    "remoteGatewayId": 0,
    "viewXml": false,
    "configXml": false,
    "interfaces": [
      "deviceGrouping",
      "energy",
      "fibaroFirmwareUpdate",
      "levelChange",
      "light",
      "power",
      "zwave",
      "zwaveSwitchAll"
    ],
    "properties": {
      "pollingTimeSec": 0,
      "zwaveCompany": "Fibargroup",
      "zwaveInfo": "3,3,52",
      "zwaveVersion": "25.25",
      "associationMode": "0",
      "brightness": "0",
      "buttonType": "0",
      "categories": "[\"lights\"]",
      "color": "0,0,0,0",
      "configured": true,
      "currentProgram": "0",
      "currentProgramID": "0",
      "dead": "false",
      "deadReason": "",
      "deviceControlType": "50",
      "deviceGroup": "[]",
      "deviceGroupMaster": "0",
      "deviceIcon": "15",
      "emailNotificationID": "0",
      "emailNotificationType": "0",
      "endPointId": "0",
      "energy": "34.37",
      "favoriteProgram": "0",
      "firmwareUpdate": "{\"info\":\"\",\"progress\":0,\"status\":\"UpToDate\",\"updateVersion\":\"25.25\"}",
      "isLight": "true",
      "lastColorSet": "0,0,0,0",
      "log": "",
      "logTemp": "",
      "manufacturer": "",
      "markAsDead": "true",
      "mode": "0",
      "model": "",
      "nodeId": "4",
      "parametersTemplate": "256",
      "power": "0.00",
      "productInfo": "1,15,9,0,64,0,25,25",
      "programsSortOrder": "1,2,3,4,5",
      "pushNotificationID": "0",
      "pushNotificationType": "0",
      "rememberColor": "false",
      "remoteGatewayId": "0",
      "saveLogs": "true",
      "serialNumber": "",
      "showEnergy": "true",
      "smsNotificationID": "0",
      "smsNotificationType": "0",
      "switchAllMode": "SWITCH_ALL_INCLUDED_IN_THE_ALL_ON_ALL_OFF_FUNCTIONALITY",
      "updateVersion": "",
      "useTemplate": "true",
      "userDescription": "",
      "value": "0"
    },
    "actions": {
      "abortUpdate": 1,
      "reconfigure": 0,
      "reset": 0,
      "retryUpdate": 1,
      "setB": 1,
      "setBrightness": 1,
      "setColor": 1,
      "setFavoriteProgram": 2,
      "setG": 1,
      "setR": 1,
      "setValue": 1,
      "setW": 1,
      "startLevelDecrease": 0,
      "startLevelIncrease": 0,
      "startProgram": 1,
      "startUpdate": 1,
      "stopLevelChange": 0,
      "turnOff": 0,
      "turnOn": 0,
      "updateFirmware": 1
    },
    "created": 1702301096,
    "modified": 1702301096,
    "sortOrder": 21
  },

```

**Comment by Savier** [comment]
Судя по всему контроллер решает что статус "Нет ответа" уже после запроса к родному контроллеру `/api/devices?enabled=true` Вот кусочек ответа про устройство в таком состоянии, если скажете что смущает контроллер, я мог бы проверить
<details>

```json
  {
    "id": 20,
    "name": "20",
    "roomID": 0,
    "type": "com.fibaro.zwaveDevice",
    "baseType": "com.fibaro.device",
    "enabled": true,
    "visible": false,
    "isPlugin": false,
    "parentId": 1,
    "remoteGatewayId": 0,
    "viewXml": false,
    "configXml": false,
    "interfaces": [
      "zwave",
      "zwaveAssociation",
      "zwaveConfiguration",
      "zwaveSlaveRouting"
    ],
    "properties": {
      "categories": "[\"other\"]",
      "configured": true,
      "dead": "false",
      "deadReason": "",
      "deviceControlType": "0",
      "deviceIcon": "28",
      "deviceSpecificData": "",
      "deviceSpecificIdType": "",
      "deviceState": "Configured",
      "emailNotificationID": "0",
      "emailNotificationType": "0",
      "endPointId": "0",
      "lastWorkingRoute": "[1]",
      "lastWorkingRouteRequestStatus": "ok",
      "lastWorkingRouteRequestTimestamp": "0",
      "lastWorkingRouteResponseTimestamp": "1702301157",
      "log": "",
      "logTemp": "",
      "manufacturer": "",
      "markAsDead": "true",
      "model": "",
      "neighborList": "[1,4,13,27,34,41,48,55,62,73]",
      "neighborListRequestStatus": "ok",
      "neighborListRequestTimestamp": "0",
      "neighborListResponseTimestamp": "1702301157",
      "nodeId": "4",
      "parameters": [
        {
          "id": 1,
          "lastReportedValue": 255,
          "lastSetValue": 255,
          "size": 1,
          "value": 255
        },
        {
          "id": 8,
          "lastReportedValue": 0,
          "lastSetValue": 0,
          "size": 1,
          "value": 0
        },
        {
          "id": 9,
          "lastReportedValue": 1,
          "lastSetValue": 1,
          "size": 1,
          "value": 1
        },
        {
          "id": 10,
          "lastReportedValue": 10,
          "lastSetValue": 10,
          "size": 2,
          "value": 10
        },
        {
          "id": 11,
          "lastReportedValue": 67,
          "lastSetValue": 67,
          "size": 1,
          "value": 67
        },
        {
          "id": 12,
          "lastReportedValue": 255,
          "lastSetValue": 255,
          "size": 1,
          "value": 255
        },
        {
          "id": 13,
          "lastReportedValue": 2,
          "lastSetValue": 2,
          "size": 1,
          "value": 2
        },
        {
          "id": 15,
          "lastReportedValue": 1,
          "lastSetValue": 1,
          "size": 1,
          "value": 1
        },
        {
          "id": 16,
          "lastReportedValue": 1,
          "lastSetValue": 1,
          "size": 1,
          "value": 1
        },
        {
          "id": 30,
          "lastReportedValue": 0,
          "lastSetValue": 0,
          "size": 1,
          "value": 0
        },
        {
          "id": 38,
          "lastReportedValue": 10,
          "lastSetValue": 10,
          "size": 1,
          "value": 10
        },
        {
          "id": 39,
          "lastReportedValue": 600,
          "lastSetValue": 600,
          "size": 2,
          "value": 600
        },
        {
          "id": 44,
          "lastReportedValue": 30,
          "lastSetValue": 30,
          "size": 2,
          "value": 30
        },
        {
          "id": 45,
          "lastReportedValue": 10,
          "lastSetValue": 10,
          "size": 1,
          "value": 10
        },
        {
          "id": 71,
          "lastReportedValue": 1,
          "lastSetValue": 1,
          "size": 1,
          "value": 1
        },
        {
          "id": 73,
          "lastReportedValue": 0,
          "lastSetValue": 0,
          "size": 1,
          "value": 0
        },
        {
          "id": 6,
          "lastReportedValue": 0,
          "lastSetValue": 0,
          "size": 1,
          "value": 0
        },
        {
          "id": 14,
          "lastReportedValue": 4369,
          "lastSetValue": 4369,
          "size": 2,
          "value": 4369
        },
        {
          "id": 42,
          "lastReportedValue": 2,
          "lastSetValue": 2,
          "size": 1,
          "value": 2
        }
      ],
      "parametersTemplate": "256",
      "pollingTimeSec": 0,
      "productInfo": "1,15,9,0,64,0,25,25",
      "pushNotificationID": "0",
      "pushNotificationType": "0",
      "remoteGatewayId": "0",
      "saveLogs": "true",
      "serialNumber": "",
      "smsNotificationID": "0",
      "smsNotificationType": "0",
      "useTemplate": "true",
      "userDescription": "",
      "zwaveCompany": "Fibargroup",
      "zwaveInfo": "3,3,52",
      "zwaveSoftwareVersion": "{}",
      "zwaveVersion": "25.25"
    },
    "actions": {
      "getLastWorkingRoute": 0,
      "getNeighborList": 0,
      "getParameter": 1,
      "reconfigure": 0,
      "requestNodeNeighborUpdate": 0,
      "setParameter": 2
    },
    "created": 1702301095,
    "modified": 1702301095,
    "sortOrder": 20
  },
  {
    "id": 21,
    "name": "Спальня кровать",
    "roomID": 4,
    "type": "com.fibaro.FGRGBW441M",
    "baseType": "com.fibaro.colorController",
    "enabled": true,
    "visible": true,
    "isPlugin": false,
    "parentId": 20,
    "remoteGatewayId": 0,
    "viewXml": false,
    "configXml": false,
    "interfaces": [
      "deviceGrouping",
      "energy",
      "fibaroFirmwareUpdate",
      "levelChange",
      "light",
      "power",
      "zwave",
      "zwaveSwitchAll"
    ],
    "properties": {
      "pollingTimeSec": 0,
      "zwaveCompany": "Fibargroup",
      "zwaveInfo": "3,3,52",
      "zwaveVersion": "25.25",
      "associationMode": "0",
      "brightness": "0",
      "buttonType": "0",
      "categories": "[\"lights\"]",
      "color": "0,0,0,0",
      "configured": true,
      "currentProgram": "0",
      "currentProgramID": "0",
      "dead": "false",
      "deadReason": "",
      "deviceControlType": "50",
      "deviceGroup": "[]",
      "deviceGroupMaster": "0",
      "deviceIcon": "15",
      "emailNotificationID": "0",
      "emailNotificationType": "0",
      "endPointId": "0",
      "energy": "34.37",
      "favoriteProgram": "0",
      "firmwareUpdate": "{\"info\":\"\",\"progress\":0,\"status\":\"UpToDate\",\"updateVersion\":\"25.25\"}",
      "isLight": "true",
      "lastColorSet": "0,0,0,0",
      "log": "",
      "logTemp": "",
      "manufacturer": "",
      "markAsDead": "true",
      "mode": "0",
      "model": "",
      "nodeId": "4",
      "parametersTemplate": "256",
      "power": "0.00",
      "productInfo": "1,15,9,0,64,0,25,25",
      "programsSortOrder": "1,2,3,4,5",
      "pushNotificationID": "0",
      "pushNotificationType": "0",
      "rememberColor": "false",
      "remoteGatewayId": "0",
      "saveLogs": "true",
      "serialNumber": "",
      "showEnergy": "true",
      "smsNotificationID": "0",
      "smsNotificationType": "0",
      "switchAllMode": "SWITCH_ALL_INCLUDED_IN_THE_ALL_ON_ALL_OFF_FUNCTIONALITY",
      "updateVersion": "",
      "useTemplate": "true",
      "userDescription": "",
      "value": "0"
    },
    "actions": {
      "abortUpdate": 1,
      "reconfigure": 0,
      "reset": 0,
      "retryUpdate": 1,
      "setB": 1,
      "setBrightness": 1,
      "setColor": 1,
      "setFavoriteProgram": 2,
      "setG": 1,
      "setR": 1,
      "setValue": 1,
      "setW": 1,
      "startLevelDecrease": 0,
      "startLevelIncrease": 0,
      "startProgram": 1,
      "startUpdate": 1,
      "stopLevelChange": 0,
      "turnOff": 0,
      "turnOn": 0,
      "updateFirmware": 1
    },
    "created": 1702301096,
    "modified": 1702301096,
    "sortOrder": 21
  },

```

</details>

**Comment by Savier** [comment]
Уточнил воспроизведение проблемы, понял что ситуация происходит только после перезагрузки хаба (в том числе при любом обновлении)

**Comment by Batyushin** [comment]
есть проблема еще актуальна просьба отписать в чат технической поддержки спрутхаба. там эти вопросы решаются в режиме реального времени
